import { StyleSheet } from "react-native";

export default StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: "#000000" },
  container: { flex: 1, backgroundColor: "#000000" },
  content: { paddingHorizontal: 20, paddingTop: 20, paddingBottom: 40 },

  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 20,
  },
  title: { fontSize: 35, fontWeight: "800", color: "#ffffff" },
  avatarCircle: {
    width: 52,
    height: 52,
    borderRadius: 25,
    backgroundColor: "#0D2137",
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 2,
    borderColor: "#7EB8F7",
  },

  statsRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 20,
    gap: 8,
  },
  statPill: {
    flex: 1,
    borderRadius: 14,
    paddingVertical: 12,
    paddingHorizontal: 8,
    alignItems: "center",
  },
  statValue: {
    fontSize: 18,
    fontWeight: "800",
    marginBottom: 2,
    color: "#000000",
  },
  statLabel: {
    fontSize: 12,
    color: "rgb(0,0,0)",
    textAlign: "center",
    fontWeight: "600",
  },

  motivationCard: {
    borderRadius: 16,
    padding: 18,
    marginBottom: 20,
    borderWidth: 2,
    borderColor: "#7EB8F7",
  },
  motivationQuote: {
    fontSize: 17,
    fontWeight: "800",
    color: "#ffffff",
    marginBottom: 5,
  },
  motivationSub: { fontSize: 16, color: "#acd0f6", fontWeight: "500" },

  sectionHeader: {
    fontSize: 12,
    fontWeight: "700",
    color: "#cfcdcd",
    letterSpacing: 1.2,
    textTransform: "uppercase",
    marginBottom: 10,
    marginTop: 4,
  },

  toggle: {
    flexDirection: "row",
    backgroundColor: "#7EB8F7",
    borderRadius: 9,
    padding: 3,
    marginBottom: 12,
  },
  toggleBtn: {
    flex: 1,
    paddingVertical: 8,
    borderRadius: 9,
    alignItems: "center",
  },
  toggleBtnActive: { backgroundColor: "#173454" },
  toggleText: { fontSize: 14, fontWeight: "600", color: "#000000" },
  toggleTextActive: { color: "#ffffff" },

  chartCard: {
    backgroundColor: "#173454",
    borderRadius: 16,
    padding: 14,
    marginBottom: 24,
    overflow: "hidden",
  },
  chartTitle: {
    fontSize: 14,
    color: "#ffffff",
    fontWeight: "600",
    marginBottom: 8,
  },
  chart: { marginLeft: -25 },

  gridWeekLabel: { fontSize: 14, color: "#ffffff", fontWeight: "700" },
  gridDayLabel: {
    fontSize: 14,
    color: "#ffffff",
    fontWeight: "600",
    textAlign: "right",
  },
  streakCell: { borderRadius: 3 },
  legendRow: { flexDirection: "row", gap: 16, marginTop: 10 },
  legendItem: { flexDirection: "row", alignItems: "center", gap: 5 },
  legendDot: { width: 12, height: 12, borderRadius: 3 },
  legendLabel: { fontSize: 14, color: "#ffffff", fontWeight: "500" },

  backdrop: { backgroundColor: "rgba(0,0,0,0.72)" },
  panel: {
    position: "absolute",
    top: 0,
    bottom: 0,
    right: 0,
    backgroundColor: "#080808",
    borderLeftWidth: 1,
    borderLeftColor: "#111111",
    shadowColor: "#000",
    shadowOffset: { width: -4, height: 0 },
    shadowOpacity: 0.6,
    shadowRadius: 20,
    elevation: 20,
  },
  panelContent: { paddingHorizontal: 18, paddingBottom: 40, paddingTop: 16 },
  panelHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    marginBottom: 24,
  },
  panelCloseBtn: {
    width: 36,
    height: 36,
    borderRadius: 10,
    backgroundColor: "#111111",
    justifyContent: "center",
    alignItems: "center",
  },
  panelCloseIcon: { color: "#7EB8F7", fontSize: 18, fontWeight: "600" },
  panelTitle: { fontSize: 20, fontWeight: "800", color: "#ffffff" },

  profileCard: {
    backgroundColor: "#173454",
    borderRadius: 16,
    padding: 16,
    alignItems: "center",
    marginBottom: 10,
    borderWidth: 1,
    borderColor: "#111111",
  },
  profileName: {
    fontSize: 16,
    fontWeight: "700",
    color: "#ffffff",
    marginBottom: 3,
  },
  profileSince: { fontSize: 13, color: "#cfcdcd" },

  panelSectionLabel: {
    fontSize: 12,
    fontWeight: "700",
    color: "#7EB8F7",
    letterSpacing: 1.4,
    marginBottom: 8,
    marginTop: 10,
  },
  settingsGroup: {
    backgroundColor: "#1d2025",
    borderRadius: 14,
    paddingHorizontal: 14,
    marginBottom: 10,
  },
  settingRow: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 13,
  },
  settingLabel: {
    fontSize: 14,
    fontWeight: "600",
    color: "#ffffff",
    marginBottom: 3,
  },
  settingSub: { fontSize: 12, color: "#7EB8F7", fontWeight: "600" },
  divider: { height: StyleSheet.hairlineWidth, backgroundColor: "#1E1E1E" },
  actionIcon: { color: "#7EB8F7", fontSize: 18 },

  freqOption: {
    flexDirection: "row",
    alignItems: "flex-start",
    paddingVertical: 10,
    paddingHorizontal: 4,
    gap: 12,
  },
  freqRadio: {
    width: 18,
    height: 18,
    borderRadius: 9,
    borderWidth: 2,
    borderColor: "#3A5A7A",
    justifyContent: "center",
    alignItems: "center",
    marginTop: 1,
  },
  freqRadioActive: { borderColor: "#7EB8F7" },
  freqRadioDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: "#7EB8F7",
  },
  freqLabel: {
    fontSize: 13,
    fontWeight: "600",
    color: "#9ABEDE",
    marginBottom: 2,
  },
  freqDesc: { fontSize: 12, color: "#5A7A9E", lineHeight: 17 },
});
