import { StyleSheet } from "react-native";
import { Colours, Radius, HeaderTitle } from "../styles/global";

export default StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: Colours.bgPrimary },
  container: { flex: 1, backgroundColor: Colours.bgPrimary },
  content: { paddingHorizontal: 20, paddingTop: 20, paddingBottom: 40 },

  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 20,
  },
  title: {
    ...HeaderTitle.title,
  },
  avatarCircle: {
    width: 52,
    height: 52,
    borderRadius: 25,
    backgroundColor: Colours.bgInput,
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 2,
    borderColor: Colours.brandBlue,
  },

  statsRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 20,
    gap: 8,
  },
  statPill: {
    flex: 1,
    borderRadius: Radius.lg,
    paddingVertical: 12,
    paddingHorizontal: 8,
    alignItems: "center",
  },
  statValue: {
    fontSize: 18,
    fontWeight: "800",
    marginBottom: 2,
    color: Colours.bgPrimary,
  },
  statLabel: {
    fontSize: 12,
    color: Colours.bgPrimary,
    textAlign: "center",
    fontWeight: "600",
  },

  motivationCard: {
    borderRadius: Radius.xl,
    padding: 18,
    marginBottom: 20,
    borderWidth: 2,
    borderColor: Colours.brandBlue,
  },
  motivationQuote: {
    fontSize: 17,
    fontWeight: "800",
    color: Colours.textPrimary,
    marginBottom: 5,
  },
  motivationSub: { fontSize: 16, color: Colours.textMuted, fontWeight: "500" },

  sectionHeader: {
    fontSize: 12,
    fontWeight: "700",
    color: Colours.textSecondary,
    textTransform: "uppercase",
    marginBottom: 10,
    marginTop: 4,
  },

  toggle: {
    flexDirection: "row",
    backgroundColor: Colours.brandBlue,
    borderRadius: Radius.sm,
    padding: 3,
    marginBottom: 12,
  },
  toggleBtn: {
    flex: 1,
    paddingVertical: 8,
    borderRadius: Radius.sm,
    alignItems: "center",
  },
  toggleBtnActive: { backgroundColor: Colours.bgCard },
  toggleText: { fontSize: 14, fontWeight: "600", color: Colours.bgPrimary },
  toggleTextActive: { color: Colours.textPrimary },

  chartCard: {
    backgroundColor: Colours.bgCard,
    borderRadius: Radius.xl,
    padding: 14,
    marginBottom: 24,
    overflow: "hidden",
  },
  chartTitle: {
    fontSize: 14,
    color: Colours.textPrimary,
    fontWeight: "600",
    marginBottom: 8,
  },
  chart: { marginLeft: -25 },

  gridWeekLabel: {
    fontSize: 14,
    color: Colours.textPrimary,
    fontWeight: "700",
  },
  gridDayLabel: {
    fontSize: 14,
    color: Colours.textPrimary,
    fontWeight: "600",
    textAlign: "right",
  },
  streakCell: { borderRadius: 3 },
  legendRow: { flexDirection: "row", gap: 16, marginTop: 10 },
  legendItem: { flexDirection: "row", alignItems: "center", gap: 5 },
  legendDot: { width: 12, height: 12, borderRadius: 3 },
  legendLabel: { fontSize: 14, color: Colours.textPrimary, fontWeight: "500" },

  backdrop: { backgroundColor: Colours.backdropColor },
  panel: {
    position: "absolute",
    top: 0,
    bottom: 0,
    right: 0,
    backgroundColor: Colours.bgSecondary,
    borderLeftWidth: 1,
    borderLeftColor: Colours.borderSubtle,
    shadowColor: Colours.bgPrimary,
    shadowOffset: { width: -4, height: 0 },
    shadowOpacity: 0.6,
    shadowRadius: 20,
    elevation: 20,
  },
  panelContent: { paddingHorizontal: 18, paddingBottom: 40, paddingTop: 16 },
  panelHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    marginBottom: 24,
  },
  panelCloseBtn: {
    width: 36,
    height: 36,
    borderRadius: Radius.md,
    backgroundColor: Colours.borderSubtle,
    justifyContent: "center",
    alignItems: "center",
  },
  panelCloseIcon: { color: Colours.brandBlue, fontSize: 18, fontWeight: "600" },
  panelTitle: { fontSize: 20, fontWeight: "800", color: Colours.textPrimary },

  profileCard: {
    backgroundColor: Colours.bgCard,
    borderRadius: Radius.xl,
    padding: 16,
    alignItems: "center",
    marginBottom: 10,
    borderWidth: 1,
    borderColor: Colours.borderSubtle,
  },
  profileName: {
    fontSize: 16,
    fontWeight: "700",
    color: Colours.textPrimary,
    marginBottom: 3,
  },
  profileSince: { fontSize: 13, color: Colours.textSecondary },

  panelSectionLabel: {
    fontSize: 12,
    fontWeight: "700",
    color: Colours.brandBlue,
    marginBottom: 8,
    marginTop: 10,
  },
  settingsGroup: {
    backgroundColor: Colours.bgCardDark,
    borderRadius: Radius.lg,
    paddingHorizontal: 14,
    marginBottom: 10,
  },
  settingRow: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 13,
  },
  settingLabel: {
    fontSize: 14,
    fontWeight: "600",
    color: Colours.textPrimary,
    marginBottom: 3,
  },
  settingSub: { fontSize: 12, color: Colours.brandBlue, fontWeight: "600" },
  divider: {
    height: StyleSheet.hairlineWidth,
    backgroundColor: Colours.borderMid,
  },
  actionIcon: { color: Colours.brandBlue, fontSize: 18 },

  freqOption: {
    flexDirection: "row",
    alignItems: "flex-start",
    paddingVertical: 10,
    paddingHorizontal: 4,
    gap: 12,
  },
  freqRadio: {
    width: 18,
    height: 18,
    borderRadius: 9,
    borderWidth: 2,
    borderColor: Colours.brandBlueDim,
    justifyContent: "center",
    alignItems: "center",
    marginTop: 1,
  },
  freqRadioActive: { borderColor: Colours.brandBlue },
  freqRadioDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: Colours.brandBlue,
  },
  freqLabel: {
    fontSize: 13,
    fontWeight: "600",
    color: Colours.textMuted,
    marginBottom: 2,
  },
  freqDesc: { fontSize: 12, color: Colours.textDisabled, lineHeight: 17 },
});
